# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  imageName: 'Noots'
  DOCKER_BUILDKIT: 1
    
steps:
- task: Docker@2
  displayName: Build client angukal
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: webClient.dockerfile

- task: Docker@2
  displayName: Build writeAPI
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: writeAPI.dockerfile
