version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - '15672:15672'
      - '5672:5672'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: 'elasticsearch'
    restart: always
    environment:
      discovery.type: single-node
    expose:
      - "9200"
    
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
        - 27017:27017

  noots-web:
    image: davydq/noots-web
    container_name: 'noots-web'
    ports:
      - "80:80"

  noots-api:
    image: davydq/noots-api
    container_name: 'noots-api'
    ports:
      - "5000:80"
    environment: 
      Mongo:client:HostName: "mongodb"

  worker:
    image: davydq/worker
    container_name: 'worker'
    environment:
      Rabbit: "amqp://guest:guest@localhost:5672"