version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - '15672:15672'
      - '5672:5672'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: 'elasticsearch'
    restart: always
    environment:
      discovery.type: single-node
    expose:
      - "9200"

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  noots-web:
    image: davydq/noots-web
    container_name: 'noots-web'
    ports:
      - "80:80"

  noots-api:
    image: davydq/noots-api
    container_name: 'noots-api'
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    environment: 
      Rabbit: "rabbitmq"
      Mongo:Host: "mongodb"
      elasticsearch:url: "http://elasticsearch:9200"

  worker:
    image: davydq/worker
    container_name: 'worker'
    restart: on-failure
    depends_on:
      - mongodb
    environment: 
      Rabbit: "rabbitmq"
      Mongo:Host: "mongodb"
      elasticsearch:url: "http://elasticsearch:9200"