version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - '15672:15672'
      - '5672:5672'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: 'elasticsearch'
    restart: always
    environment:
      discovery.type: single-node
    expose:
      - "9200"
    
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
        - 27017:27017