version: "3"

services:
  noots-balancer:
    container_name: noots-balancer
    image: noots-balancer
    ports:
      - "80:80"
    depends_on:
      - "noots-static"
  noots-static:
    container_name: noots-static
    image: noots-static
    depends_on:
      - "noots-api"
  noots-api:
    # container_name: noots-api - prohibited for replicas use container-name
    image: noots-api
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - Redis:Active=false
      - Redis:Connection=http://host.docker.internal:6379
    deploy:
      replicas: 1
  noots-api-2:
    # container_name: noots-api - prohibited for replicas use container-name
    image: noots-api
    environment:
      - ASPNETCORE_URLS=http://+:5005
      - Redis:Active=false
      - Redis:Connection=http://host.docker.internal:6379
    deploy:
      replicas: 1
  noots-worker-api:
    container_name: noots-worker-api
    image: noots-worker-api
    ports:
      - "5600:5600"
  noots-health-check-api:
    container_name: noots-health-check-api
    image: noots-health-check-api
    environment:
      - ASPNETCORE_URLS=http://+:5900;http://+:5950
    ports:
      - "5900:5900"
      - "5950:5950"
#  redis:
#    image: redis/redis-stack
#    ports:
#      - 6379:6379
#    restart: unless-stopped

# volumes:
#   redis_data: