properties:
  configuration:
    ingress:
      external: true
      allowInsecure: false
      targetPort: 5000
      stickySessions:
        affinity: sticky
    dapr:
      appId: web
      appPort: 5000
      appProtocol: http
      enabled: true