properties:
    managedEnvironmentId: /subscriptions/ada8dd43-100d-4c2f-86f9-dfa526804584/resourceGroups/Noots-DEV/providers/Microsoft.App/managedEnvironments/managedEnvironment-NootsDEV-bd5e
    configuration:
      ingress:
        external: true
        allowInsecure: false
        targetPort: 80
      dapr:
        appId: x-notes-health-check-api
        appPort: 80
        appProtocol: http
        enabled: true