properties:
    managedEnvironmentId: /subscriptions/ada8dd43-100d-4c2f-86f9-dfa526804584/resourceGroups/Noots-DEV/providers/Microsoft.App/managedEnvironments/managedEnvironment-NootsDEV-bd5e
    configuration:
      ingress:
        external: true
        allowInsecure: false
        targetPort: 5000
    template:
      containers:
        - image: nootsstorm/noots-api:DEV
          name: noots-api