name: CI

on: [push]

defaults:
  run:
    working-directory: ./Client

jobs:
  test:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge DEV
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git pull --no-rebase origin DEV

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Linter
        run: yarn lint
