name: Databases Migrations

on:
  push:
    branches:
      - 'DEV'

jobs:
  db-worker-migration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup .NET SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Change this to your desired .NET version

      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef --version 6.0.8

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Backend/NootsWEB/Noots.API.Workers/Noots.API.Workers.csproj

      # Run EF Core migrations
      - name: Run migrations
        run: dotnet ef database update -c ApplicationDatabaseContext -p Backend/NootsWEB/Noots.API.Workers -s Backend/NootsWEB/Noots.API.Workers
        env:
          DatabaseConnection: ${{ secrets.DEV_NOOTS_WORKER_DB_CONNECTION }} # Store your connection string as a secret in your repository settings
          NootsDatabaseConnection: ${{ secrets.DEV_NOOTS_API_DB_CONNECTION  }}

  db-health-check-migration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup .NET SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Change this to your desired .NET version

      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef --version 6.0.8

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Backend/HealthCheckerWEB/HealthCheckWEB/HealthCheckWEB.csproj

      # Run EF Core migrations
      - name: Run migrations
        run: dotnet ef database update -c ApplicationDatabaseContext -p Backend/HealthCheckerWEB/HealthCheckWEB -s Backend/HealthCheckerWEB/HealthCheckWEB
        env:
          NootsDB: ${{ secrets.DEV_NOOTS_API_DB_CONNECTION }} # Store your connection string as a secret in your repository settings
          NootsWorkersDB: ${{ secrets.DEV_NOOTS_WORKER_DB_CONNECTION  }}
          HealthCheckerDatabaseConn: ${{ secrets.DEV_NOOTS_HEALTH_CHECK_DB_CONNECTION }}