name: Release

on:
  push:
    branches:
      - DEV
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./Client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        working-directory: ./Client
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
